"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_router_dom_1 = require("react-router-dom");
var elements_1 = require("./elements");
var Grid_1 = require("@material-ui/core/Grid");
var Box_1 = require("@material-ui/core/Box");
exports.HomePage = function () { return (React.createElement("div", null,
    React.createElement(elements_1.MainHeader, { as: "h1" }, "WebDev Lessons"),
    React.createElement(elements_1.MainSubHeader, { as: "h2" }, "(Lessons in Website Development)"),
    React.createElement(Grid_1.default, { container: true },
        React.createElement(Grid_1.default, { item: true, sm: 12 },
            React.createElement(elements_1.HeadersContainer, null,
                React.createElement(Box_1.default, { justifyContent: { sm: 'center' } },
                    React.createElement(Grid_1.default, { item: true },
                        React.createElement("h2", { className: "welcome-h2 text-wrap col-sm-auto" }, "Welcome to WebDev Lessons!"))),
                React.createElement("div", { className: "row justify-content-md-center" },
                    React.createElement("h3", { className: "welcome-h3 text-wrap col-sm-auto" }, "Learn JavaScript, HTML, CSS, and more!"))))),
    React.createElement("div", { className: "content" },
        React.createElement("div", { className: "iframe-container-intro embed-responsive embed-responsive-4by3" },
            React.createElement("iframe", { width: "640", height: "360", src: "https://www.youtube.com/embed/nLNzeoFjCSU", frameBorder: "0", allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", allowFullScreen: true })),
        React.createElement("div", { className: "iframe-container-intro embed-responsive embed-responsive-4by3" },
            React.createElement("iframe", { src: "https://player.vimeo.com/video/308895468", width: "640", height: "360", frameBorder: "0", allowFullScreen: true }))),
    React.createElement("h3", { className: "home-page-h3" }, "Check out the Introduction Overview page to see a full list of our courses"),
    React.createElement(react_router_dom_1.Link, { to: "/courses/" },
        React.createElement("button", { className: "navbarLink lg-btn" }, "Courses")),
    React.createElement("div", { className: "xs-spacer" }),
    React.createElement("h3", { className: "home-page-h3" },
        "Have a question? Contact\u00A0us\u00A0",
        React.createElement("div", { className: "green-accent-link" },
            React.createElement(react_router_dom_1.Link, { to: "/about/" },
                React.createElement("div", { className: "green-accent-link home-page-h3" }, "here")))),
    React.createElement("div", { className: "container" },
        React.createElement("div", { className: "row justify-content-center d-none d-lg-inline" },
            React.createElement("div", { id: "carousel", className: "carousel slide", "data-pause": "hover", "data-ride": "carousel" },
                React.createElement("div", { className: "carousel-inner" },
                    React.createElement("div", { className: "carousel-item active" },
                        React.createElement("div", { className: "container" },
                            React.createElement("div", { className: "row" },
                                React.createElement("div", { className: "col-12" },
                                    React.createElement("div", { className: "c-headshot-container" },
                                        React.createElement("img", { src: "./../../images/slack-logo-icon.png" })),
                                    React.createElement("h3", { className: "c-header" }, "Join our Slack group!"),
                                    React.createElement("p", { className: "c-paragraph" }, "Ask questions, learn from other WebDev Lessons coders, and get notified when a new lesson\u00A0is\u00A0available."),
                                    React.createElement("a", { href: "https://join.slack.com/t/webdev-lessons/shared_invite/enQtNTE1NjQyNDcxNDE1LWFmZGExNGNjNzQ0OWYzOTQ2MGRhYjBiMGQ0NWE5ODJkMTA0NTNlNjE1Yzc2NTcyODZmMjY1MTE3M2RhOWY1YTk", target: "_blank" },
                                        React.createElement("button", null, "Join now!")))))),
                    React.createElement("div", { className: "carousel-item" },
                        React.createElement("div", { className: "container" },
                            React.createElement("div", { className: "row" },
                                React.createElement("div", { className: "col-9" },
                                    React.createElement("h3", { className: "c-header-smaller" }, "Help us continue to deliver free content!"),
                                    React.createElement("p", { className: "c-paragraph-smaller" },
                                        "We work hard to ensure that your coding experience with us is of the utmost quality. Help us increase that quality and keep the content free at the same time. \uD83D\uDE09 Every\u00A0little\u00A0bit\u00A0helps!",
                                        React.createElement("br", null),
                                        React.createElement("span", { className: "signature" }, "-Bruce Johnson (WebDev Lessons Instructor)"))),
                                React.createElement("div", { className: "col-3 margin-top" },
                                    React.createElement("form", { action: "https://www.paypal.com/cgi-bin/webscr", method: "post", target: "_blank" },
                                        React.createElement("input", { type: "hidden", name: "cmd", value: "_donations" }),
                                        React.createElement("input", { type: "hidden", name: "business", value: "8F5H897B2D9QG" }),
                                        React.createElement("input", { type: "hidden", name: "currency_code", value: "USD" }),
                                        React.createElement("input", { type: "image", src: "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif", style: { border: 0 }, name: "submit", title: "PayPal - The safer, easier way to pay online!", alt: "Donate with PayPal button" }),
                                        React.createElement("img", { alt: "", style: { border: 0 }, src: "https://www.paypal.com/en_US/i/scr/pixel.gif", width: "1", height: "1" }))))))),
                React.createElement("a", { className: "carousel-control-prev", href: "#carousel", role: "button", "data-slide": "prev" },
                    React.createElement("span", { className: "carousel-control-prev-icon", "aria-hidden": "true" }),
                    React.createElement("span", { className: "sr-only" }, "Previous")),
                React.createElement("a", { className: "carousel-control-next", href: "#carousel", role: "button", "data-slide": "next" },
                    React.createElement("span", { className: "carousel-control-next-icon", "aria-hidden": "true" }),
                    React.createElement("span", { className: "sr-only" }, "Next"))))))); };
